config/routes.rb
Rails.application.routes.draw do

  resources :working_days

  resources :expenses

  resources :payments

  resources :name_expenses

  resources :providers
  
  get 'last_payments/:limit(.:format)' => 'payments#last_payments'
  
  get 'active_payments' => 'payments#active_payments'
  
  get 'payments_by_provider/:provider(.:format)' => 'payments#by_provider'
  get 'expenses_by_name/:name(.:format)' => 'expenses#by_name'
  get 'working_days_by_date/:day_date(.:format)' => 'working_days#by_date'
  
  get 'payments_by_day/:day(.:format)' => 'payments#by_day'
  get 'expenses_by_day/:day(.:format)' => 'expenses#by_day'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  # GET /last_paymentsjson
  def last_payments
    @last_payments = Payment.last(params[:limit]) 
  end
  
  def by_provider
    provider_spaces =params[:provider]
    provider_spaces=provider_spaces.tr("_", " ")
   # provider_spaces=provider_spaces.tr("%C3%B1", "ñ")
#    @payments_provider =  Payment.where("provider = ?",provider_spaces).order(day_date: :desc)
    @payments_provider =  Payment.where(:provider => provider_spaces).order(day_date: :desc)

  end
  def by_day
    @payments_by_day =  Payment.where(:day_date => params[:day]).order(:provider)
  end  
  # GET active_payments'
  def active_payments
    @active_payments =  Payment.where("state is true")
  end 
  
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :provider, :state, :day_date)
    end
    
 #   def authenticate
 #    authenticate_or_request_with_http_basic do |name, password|
#       name=="prueba"&& password=="prueba"
 #    end
      
 #   end  
 
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :day_date %><br>
    <%= f.number_field :day_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/active_payments.html.erb
<h1>Listing Active payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Provider</th>
      <th>State</th>
      <th>Day date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.provider %></td>
        <td><%= payment.state %></td>
        <td><%= payment.day_date %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/by_day.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Provider</th>
      <th>State</th>
      <th>Day date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments_by_day.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.provider %></td>
        <td><%= payment.state %></td>
        <td><%= payment.day_date %></td>
    
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/by_provider.html.erb
<h1>Listing Active payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Provider</th>
      <th>State</th>
      <th>Day date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments_provider.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.provider %></td>
        <td><%= payment.state %></td>
        <td><%= payment.day_date %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Provider</th>
      <th>State</th>
      <th>Day date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.provider %></td>
        <td><%= payment.state %></td>
        <td><%= payment.day_date %></td>
    
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/last_payments.html.erb
<h1>Listing last payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Provider</th>
      <th>State</th>
      <th>Day date</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @last_payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.provider %></td>
        <td><%= payment.state %></td>
        <td><%= payment.day_date %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @payment.provider %>
</p>

<p>
  <strong>State:</strong>
  <%= @payment.state %>
</p>

<p>
  <strong>Day date:</strong>
  <%= @payment.day_date %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>