config/routes.rb
Rails.application.routes.draw do

  resources :working_days

  resources :expenses

  resources :payments

  resources :name_expenses

  resources :providers
  
  get 'last_payments/:limit(.:format)' => 'payments#last_payments'
  
  get 'active_payments' => 'payments#active_payments'
  
  get 'payments_by_provider/:provider(.:format)' => 'payments#by_provider'
  get 'expenses_by_name/:name(.:format)' => 'expenses#by_name'
  get 'working_days_by_date/:day_date(.:format)' => 'working_days#by_date'
  
  get 'payments_by_day/:day(.:format)' => 'payments#by_day'
  get 'expenses_by_day/:day(.:format)' => 'expenses#by_day'

end

app/models/working_day.rb
class WorkingDay < ActiveRecord::Base
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  before_action :set_working_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  # GET /working_days
  # GET /working_days.json
  def index
    @working_days = WorkingDay.all.order(:day_date)
  end
  
  def by_date
   #  WorkingDay.where("day_date = \'"+params[:day_date]+"\'")
    @working_day_by_date = WorkingDay.where(:day_date=> params[:day_date])  
    #@working_day_by_date = WorkingDay.where (:day_date => params[:day_date])    
      
    #("day_date = \'"+params[:day_date]+"\' limit(1)")
  end
  # GET /working_days/1
  # GET /working_days/1.json
  def show
  end

  # GET /working_days/new
  def new
    @working_day = WorkingDay.new
  end

  # GET /working_days/1/edit
  def edit
  end

  # POST /working_days
  # POST /working_days.json
  def create
    @working_day = WorkingDay.new(working_day_params)

    respond_to do |format|
      if @working_day.save
        format.html { redirect_to @working_day, notice: 'Working day was successfully created.' }
        format.json { render :show, status: :created, location: @working_day }
      else
        format.html { render :new }
        format.json { render json: @working_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /working_days/1
  # PATCH/PUT /working_days/1.json
  def update
    respond_to do |format|
      if @working_day.update(working_day_params)
        format.html { redirect_to @working_day, notice: 'Working day was successfully updated.' }
        format.json { render :show, status: :ok, location: @working_day }
      else
        format.html { render :edit }
        format.json { render json: @working_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /working_days/1
  # DELETE /working_days/1.json
  def destroy
    @working_day.destroy
    respond_to do |format|
      format.html { redirect_to working_days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_working_day
      @working_day = WorkingDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def working_day_params
      params.require(:working_day).permit(:day_date, :sale, :cash, :change_coins)
    end
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/working_days/_form.html.erb
<%= form_for(@working_day) do |f| %>
  <% if @working_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@working_day.errors.count, "error") %> prohibited this working_day from being saved:</h2>

      <ul>
      <% @working_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day_date %><br>
    <%= f.number_field :day_date %>
  </div>
  <div class="field">
    <%= f.label :sale %><br>
    <%= f.text_field :sale %>
  </div>
  <div class="field">
    <%= f.label :cash %><br>
    <%= f.text_field :cash %>
  </div>
  <div class="field">
    <%= f.label :change %><br>
    <%= f.text_field :change_coins %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/working_days/by_date.html.erb
<h1>Working day by date</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Sale</th>
      <th>Cash</th>
      <th>Change</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @working_day_by_date.each do |working_day| %>
      <tr>
        <td><%= working_day.day_date %></td>
        <td><%= working_day.sale %></td>
        <td><%= working_day.cash %></td>
        <td><%= working_day.change_coins %></td>
        <td><%= link_to 'Show', working_day %></td>
        <td><%= link_to 'Edit', edit_working_day_path(working_day) %></td>
        <td><%= link_to 'Destroy', working_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Working day', new_working_day_path %>

app/views/working_days/edit.html.erb
<h1>Editing working_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @working_day %> |
<%= link_to 'Back', working_days_path %>

app/views/working_days/index.html.erb
<h1>Listing working_days</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Sale</th>
      <th>Cash</th>
      <th>Change</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @working_days.each do |working_day| %>
      <tr>
        <td><%= working_day.day_date %></td>
        <td><%= working_day.sale %></td>
        <td><%= working_day.cash %></td>
        <td><%= working_day.change_coins %></td>
        <td><%= link_to 'Show', working_day %></td>
        <td><%= link_to 'Edit', edit_working_day_path(working_day) %></td>
        <td><%= link_to 'Destroy', working_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Working day', new_working_day_path %>

app/views/working_days/new.html.erb
<h1>New working_day</h1>

<%= render 'form' %>

<%= link_to 'Back', working_days_path %>

app/views/working_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @working_day.day_date %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @working_day.sale %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @working_day.cash %>
</p>

<p>
  <strong>Change:</strong>
  <%= @working_day.change_coins %>
</p>

<%= link_to 'Edit', edit_working_day_path(@working_day) %> |
<%= link_to 'Back', working_days_path %>