config/routes.rb
Rails.application.routes.draw do

  resources :working_days

  resources :expenses

  resources :payments

  resources :name_expenses

  resources :providers
  
  get 'last_payments/:limit(.:format)' => 'payments#last_payments'
  
  get 'active_payments' => 'payments#active_payments'
  
  get 'payments_by_provider/:provider(.:format)' => 'payments#by_provider'
  get 'expenses_by_name/:name(.:format)' => 'expenses#by_name'
  get 'working_days_by_date/:day_date(.:format)' => 'working_days#by_date'
  
  get 'payments_by_day/:day(.:format)' => 'payments#by_day'
  get 'expenses_by_day/:day(.:format)' => 'expenses#by_day'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end
  def by_name
    expense_name_spaces =params[:name]
    expense_name_spaces =expense_name_spaces .tr("_", " ")
   # provider_spaces=provider_spaces.tr("%C3%B1", "ñ")
    p expense_name_spaces
    @expenses_name =  Expense.where(:name_expense => expense_name_spaces).order(day_date: :desc)
  end
  
  def by_day
    @expenses_by_day =  Expense.where(:day_date => params[:day]).order(:name_expense)
  end
  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:amount, :name_expense, :day_date)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :day_date %><br>
    <%= f.number_field :day_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :name_expense %><br>
    <%= f.text_field :name_expense %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/by_day.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Day date</th>	
      <th>Amount</th>
      <th>Name expense</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses_by_day.each do |expense| %>
      <tr>
	    <td><%= expense.day_date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.name_expense %></td>


        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/by_name.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Day date</th>	
      <th>Amount</th>
      <th>Name expense</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses_name.each do |expense| %>
      <tr>
	    <td><%= expense.day_date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.name_expense %></td>


        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Day date</th>	
      <th>Amount</th>
      <th>Name expense</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
	    <td><%= expense.day_date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.name_expense %></td>


        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Day date:</strong>
  <%= @expense.day_date %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Name expense:</strong>
  <%= @expense.name_expense %>
</p>




<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>